### ISSUE TITLE
A website with a simple interface using the mentioned resources

### ISSUE THREAD

**Issue by chefberke** [dilarauluturhan/developer-resources#2]
As mentioned in the title, I wanted to propose an idea. While browsing the github, I suddenly found myself here and thought that it would provide a more convenient experience for those who will benefit from it. In short, a page with information, that's all.

If it is decided to do it, I would like to contribute and you think this is an unnecessary topic, please close the issue.

thanks for your time, all the best!

**Comment by dilarauluturhan** [comment]
I don't plan on doing such a project anytime soon. If I want to do it, I would like to exchange ideas with you. Thanks for the suggestion. Enjoy your work!
